import { Sparkles } from "lucide-react";

interface AISummaryCardProps {
  summary: string;
  /** ISO string or human-readable label, e.g. new Date().toLocaleString() */
  generatedAt?: string;
  model?: string;
}

/**
 * Renders the AI-generated audit summary.
 *
 * Handles multi-paragraph output from the model by splitting on newlines,
 * shows a "generated by" attribution row, and applies a subtle animated
 * gradient border to visually distinguish this card from static panels.
 */
export function AISummaryCard({
  summary,
  generatedAt,
  model = "Gemini 2.5 Flash",
}: AISummaryCardProps) {
  // Split on one or more newlines so multi-paragraph model output
  // renders as distinct paragraphs rather than a single collapsed block.
  const paragraphs = summary
    .split(/\n+/)
    .map((p) => p.trim())
    .filter(Boolean);

  return (
    <div className="relative rounded-2xl p-px overflow-hidden ai-summary-glow">
      {/* Animated gradient border — sits behind the inner card */}
      <div className="ai-summary-border-anim" aria-hidden />

      {/* Inner card */}
      <div className="relative rounded-[calc(1rem-1px)] bg-[oklch(0.13_0.025_270)] p-6">
        {/* Header row */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2.5">
            <div className="relative h-7 w-7 rounded-lg bg-gradient-brand flex items-center justify-center shrink-0">
              <Sparkles className="h-4 w-4 text-primary-foreground" />
              {/* Pulse ring */}
              <span className="absolute inset-0 rounded-lg bg-gradient-brand animate-ping opacity-20" />
            </div>
            <h3 className="font-semibold text-sm">AI-Generated Summary</h3>
          </div>

          {/* Attribution */}
          <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground font-mono">
            <span className="h-1.5 w-1.5 rounded-full bg-success animate-pulse shrink-0" />
            <span>{model}</span>
            {generatedAt && (
              <>
                <span className="opacity-40">·</span>
                <span>{generatedAt}</span>
              </>
            )}
          </div>
        </div>

        {/* Divider */}
        <div className="h-px bg-gradient-to-r from-transparent via-border to-transparent mb-4" />

        {/* Summary body — paragraph-aware */}
        <div className="space-y-3">
          {paragraphs.map((para, i) => (
            <p
              key={i}
              className="text-foreground/80 leading-relaxed text-sm"
            >
              {para}
            </p>
          ))}
        </div>

        {/* Watermark */}
        <p className="mt-4 text-[10px] text-muted-foreground/40 text-right font-mono">
          Generated by SpendWise AI
        </p>
      </div>

      <style>{`
        /* Slow-rotating conic gradient that peeks through the 1px wrapper */
        .ai-summary-border-anim {
          position: absolute;
          inset: 0;
          border-radius: inherit;
          background: conic-gradient(
            from var(--angle, 0deg),
            oklch(0.72 0.18 155),
            oklch(0.65 0.22 270),
            oklch(0.70 0.20 320),
            oklch(0.72 0.18 155)
          );
          animation: border-spin 6s linear infinite;
        }

        @property --angle {
          syntax: "<angle>";
          initial-value: 0deg;
          inherits: false;
        }

        @keyframes border-spin {
          to { --angle: 360deg; }
        }
      `}</style>
    </div>
  );
}